// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ImportTransformEntry} from "../../transformers"

export const reactTableTransforms: ImportTransformEntry[] = [
  {
    imports: [{name: "Table", renameTo: "TableInstance"}],
    sourcePackage: "@qui/table-core",
    targetPackage: "@qualcomm-ui/core/table",
  },
  {sourcePackage: "@qui/table-core", targetPackage: "@qualcomm-ui/core/table"},
  {
    imports: [
      "ColumnSizingTableState",
      "ColumnSizingState",
      "ColumnSizingInfoState",
      "ColumnResizeMode",
      "ColumnResizeDirection",
      "ColumnSizingOptions",
      "ColumnSizingDefaultOptions",
      "ColumnSizingInstance",
      "ColumnSizingColumnDef",
      "ColumnSizingColumn",
      "ColumnSizingHeader",
      "passiveEventSupported",
      "defaultColumnSizing",
      "ColumnSizing",
      "ExpandedStateList",
      "ExpandedState",
      "ExpandedTableState",
      "ExpandedRow",
      "ExpandedOptions",
      "ExpandedInstance",
      "Expanding",
      "FiltersTableState",
      "ColumnFiltersState",
      "ColumnFilter",
      "ResolvedColumnFilter",
      "FilterFn",
      "TransformFilterValueFn",
      "ColumnFilterAutoRemoveTestFn",
      "CustomFilterFns",
      "FilterFnOption",
      "FiltersColumnDef",
      "FiltersColumn",
      "FiltersRow",
      "FiltersOptions",
      "FiltersInstance",
      "shouldAutoRemoveFilter",
      "Filters",
      "GroupingState",
      "GroupingTableState",
      "AggregationFn",
      "CustomAggregationFns",
      "AggregationFnOption",
      "GroupingColumnDef",
      "GroupingColumn",
      "GroupingRow",
      "GroupingCell",
      "ColumnDefaultOptions",
      "GroupingOptions",
      "GroupingColumnMode",
      "GroupingInstance",
      "orderColumns",
      "Grouping",
      "ColumnOrderTableState",
      "ColumnOrderState",
      "ColumnOrderOptions",
      "ColumnOrderDefaultOptions",
      "ColumnOrderInstance",
      "Ordering",
      "PaginationState",
      "PaginationTableState",
      "PaginationInitialTableState",
      "PaginationOptions",
      "PaginationDefaultOptions",
      "PaginationInstance",
      "Pagination",
      "ColumnPinningPosition",
      "RowPinningPosition",
      "ColumnPinningState",
      "RowPinningState",
      "ColumnPinningTableState",
      "RowPinningTableState",
      "ColumnPinningOptions",
      "RowPinningOptions",
      "ColumnPinningDefaultOptions",
      "RowPinningDefaultOptions",
      "ColumnPinningColumnDef",
      "ColumnPinningColumn",
      "ColumnPinningRow",
      "RowPinningRow",
      "ColumnPinningInstance",
      "RowPinningInstance",
      "Pinning",
      "RowSelectionState",
      "RowSelectionTableState",
      "RowSelectionOptions",
      "RowSelectionRow",
      "RowSelectionInstance",
      "selectRowsFn",
      "isRowSelected",
      "isSubRowSelected",
      "RowSelection",
      "SortDirection",
      "ColumnSort",
      "SortingState",
      "SortingTableState",
      "SortingFn",
      "CustomSortingFns",
      "SortingFnOption",
      "SortingColumnDef",
      "SortingColumn",
      "SortingOptions",
      "SortingInstance",
      "Sorting",
      "VisibilityState",
      "VisibilityTableState",
      "VisibilityOptions",
      "VisibilityDefaultOptions",
      "VisibilityInstance",
      "VisibilityColumnDef",
      "VisibilityRow",
      "VisibilityColumn",
      "Visibility",
      "TableMeta",
      "ColumnMeta",
      "FilterMeta",
      "FilterFns",
      "SortingFns",
      "AggregationFns",
      "Updater",
      "OnChangeFn",
      "RowData",
      "AnyRender",
      "TableInstance",
      "TableOptionsResolved",
      "TableOptions",
      "TableState",
      "InitialTableState",
      "Row",
      "RowModel",
      "AccessorFn",
      "ColumnDefTemplate",
      "StringHeaderIdentifier",
      "IdIdentifier",
      "ColumnDefBase",
      "IdentifiedColumnDef",
      "DisplayColumnDef",
      "GroupColumnDef",
      "AccessorFnColumnDef",
      "AccessorKeyColumnDefBase",
      "AccessorKeyColumnDef",
      "AccessorColumnDef",
      "ColumnDef",
      "ColumnDefResolved",
      "Column",
      "Cell",
      "Header",
      "HeaderGroup",
      "CellContext",
      "CoreCell",
      "createCell",
      "CoreColumn",
      "createColumn",
      "CoreHeaderGroup",
      "HeaderContext",
      "CoreHeader",
      "HeadersInstance",
      "buildHeaderGroups",
      "Headers",
      "CoreRow",
      "createRow",
      "TableFeature",
      "CoreTableState",
      "CoreOptions",
      "CoreInstance",
      "createTable",
      "PartialKeys",
      "RequiredKeys",
      "Overwrite",
      "UnionToIntersection",
      "IsAny",
      "IsKnown",
      "DeepKeys",
      "DeepValue",
      "NoInfer",
      "Getter",
      "functionalUpdate",
      "noop",
      "makeStateUpdater",
      "isFunction",
      "isNumberArray",
      "flattenBy",
      "memo",
      "filterRows",
      "filterRowModelFromLeafs",
      "filterRowModelFromRoot",
      "getCoreRowModel",
      "getExpandedRowModel",
      "expandRows",
      "getFacetedMinMaxValues",
      "getFacetedRowModel",
      "getFacetedUniqueValues",
      "getFilteredRowModel",
      "getGroupedRowModel",
      "getPaginationRowModel",
      "getSortedRowModel",
      "BuiltInSortingFn",
      "reSplitAlphaNumeric",
      "sortingFns",
      "BuiltInAggregationFn",
      "aggregationFns",
      "ColumnHelper",
      "createColumnHelper",
      "safeDocument",
      "safeWindow",
      "BuiltInFilterFn",
      "filterFns",
    ],
    sourcePackage: "@qui/react-table",
    targetPackage: "@qualcomm-ui/core/table",
  },
  {
    imports: [
      {name: "QTableProps", renameTo: "TableRootProps"},
      {name: "QTheadProps", renameTo: "TableHeaderProps"},
      {name: "QTfootProps", renameTo: "TableFooterProps"},
      {name: "QTbodyProps", renameTo: "TableBodyProps"},
      {name: "QTrProps", renameTo: "TableRowProps"},
      {name: "QThProps", renameTo: "TableHeaderCellProps"},
      {name: "QTdProps", renameTo: "TableCellProps"},
      // duplicates will be merged out
      {name: "QTr", renameTo: "Table"},
      {name: "QTfoot", renameTo: "Table"},
      {name: "QTh", renameTo: "Table"},
      {name: "QTd", renameTo: "Table"},
      {name: "QTbody", renameTo: "Table"},
      {name: "QThead", renameTo: "Table"},
    ],
    jsxWrappers: [
      {
        name: "Table.Table",
        wrapWith: ["Table.Root", "Table.ScrollContainer"],
      },
    ],
    sourcePackage: "@qui/react-table",
    targetPackage: "@qualcomm-ui/react/table",
    variableTransformers: [
      {
        name: "QTable",
        renameTo: "Table.Table",
      },
      {
        name: "QTbody",
        renameTo: "Table.Body",
      },
      {
        name: "QTd",
        renameTo: "Table.Cell",
      },
      {
        name: "QTfoot",
        renameTo: "Table.Footer",
      },
      {
        name: "QTh",
        renameTo: "Table.HeaderCell",
      },
      {
        name: "QThead",
        renameTo: "Table.Header",
      },
      {
        name: "QTr",
        renameTo: "Table.Row",
      },
    ],
  },
  {
    imports: [{name: "QTable", renameTo: "Table"}],
    sourcePackage: "@qui/react-table",
    targetPackage: "@qui/react-table",
  },
  // adjust the remaining imports
  {
    sourcePackage: "@qui/react-table",
    targetPackage: "@qualcomm-ui/react/table",
  },
]
