// Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
// SPDX-License-Identifier: BSD-3-Clause-Clear

import type {ImportTransformEntry} from "../transformers"

export const reactRouterUtils: ImportTransformEntry[] = [
  {
    imports: [
      "updateDemoState",
      "createDemoStateUpdateAction",
      "SiteState",
      "updateSiteState",
      "createUpdateAction",
      "createThemeAction",
      "createThemeSessionResolver",
      "ThemeProvider",
      "useTheme",
      "themes",
      "Theme",
      "isTheme",
      "PreventFlashOnWrongTheme",
      "createThemeAction",
      "Theme",
      "ThemeMetadata",
      "ThemeProviderProps",
      "ThemeProvider",
      "PreventFlashOnWrongTheme",
      "useTheme",
      "isTheme",
      "Theme",
      "themes",
      "mediaQuery",
      "ThemeSessionResolver",
      "createThemeSessionResolver",
      "useBroadcastChannel",
      "useCorrectCssTransition",
    ],
    sourcePackage: "@qui/react-router-utils",
    targetPackage: "@qualcomm-ui/react-router-utils/client",
  },
  {
    imports: [
      "ConfigRoute",
      "RouteManifest",
      "DefineRouteFunction",
      "RouteInfo",
      "DefineRouteOptions",
      "DefineRouteChildren",
      "VisitFilesFunction",
      "FlatRoutesOptions",
      "DefineRoutesFunction",
      "hybridRoutes",
      "isRouteModuleFile",
      "isIndexRoute",
      "getRouteInfo",
      "createRoutePath",
      "getRouteSegments",
      "defaultVisitFiles",
      "createRouteId",
      "normalizeSlashes",
    ],
    sourcePackage: "@qui/react-router-utils",
    targetPackage: "@qualcomm-ui/react-router-utils/node",
  },
]
